### ISSUE TITLE
Simplify setColor API

### ISSUE THREAD

**Issue by mcndt** [Ennoriel/svelte-awesome-color-picker#1]
Hi!

Currently, setColor requires to pass both RGB, HSV and Hex values to set a color. This isn't very practical because it requires to precalculate the correct RGB and HSV values.

A simplified version would be to set one of the three and compute the other two inside of the component, hidden from the user.

**Comment by Ennoriel** [comment]
Hi @mcndt !

Thanks for your feedback!

It's actually already possible. The Types seems wrong but it's still possible. The exported method is defined like this:

https://github.com/Ennoriel/svelte-awesome-color-picker/blob/8c2c205087d6e9ffb242142bd2f8e9619562395c/src/lib/ColorPicker.svelte#L41-L49

I'll fix the types!

**Comment by mcndt** [comment]
I see! I should have dug a little deeper in the source, my bad.

It would be great if we can fix the types to keep TypeScript from complaining. I'll see if I have some time to make a PR.

**Comment by Ennoriel** [comment]
I actually removed the setColor props. Everything is know doable directly with the color prop.
Also, I made a documentation [site](https://svelte-awesome-color-picker.vercel.app/)! 🌟

Tell me if you find any issue with this new version!

**Comment by mcndt** [comment]
It seems like v0.0.4 introduced a new bug:

The slider no longer seems to respond to respects `--slider-width` and `--picker-height` properties.

Before:

![image](https://user-images.githubusercontent.com/23149353/150699765-07450d06-666e-4980-8ffe-bd8fcd559e8f.png)

After:

![image](https://user-images.githubusercontent.com/23149353/150699758-8d83e6d1-069b-4c59-aad7-4dfb998a6a0b.png)

**Comment by Ennoriel** [comment]
I don't even know why it worked before but I fixed it!

**Comment by mcndt** [comment]
Great thanks for the support! I'll check it out as soon as its published on npm.

**Comment by Ennoriel** [comment]
It is. 🙄
Do you still have the problem?

**Comment by mcndt** [comment]
Seems like the problem is still happening, but I noticed that the wrapper div around the slider redefines the CSS variables, causing my modified variables to be overridden:

![image](https://user-images.githubusercontent.com/23149353/150793151-7c2ca812-fac0-4bc2-9575-14a2c0e6e0a7.png)

Obviously this should be fixed in your latest commit:

https://github.com/Ennoriel/svelte-awesome-color-picker/commit/8db6ec976c66b3c806c3759dabb491063a870079#

Perhaps npm's CDN didn't invalidate the cached version of version 0.0.4 of the package, because even after clearing my NPM cache locally and reinstalling all modules, I still get the old v0.0.4 in my `node_modules`:

![image](https://user-images.githubusercontent.com/23149353/150794916-effdd0de-4081-40e4-a46a-91a6eb0fa4b3.png)

**Comment by Ennoriel** [comment]
It's a bit weird. Is it working on this [REPL](https://svelte.dev/repl/177774774cca4d9a9c271b284f288c7b?version=3.46.2) ?

I'm going to make another release with no change 😃

**Comment by mcndt** [comment]
The version bump bumped the NPM registered version from 0.0.4 to 0.0.6 and now I was able to pull the updated code without an issue. Everything works now. Thanks again!
